// packages/cli/src/codemods/transforms/transform-modules-to-packages-v33/__fixtures__/scenarios/vue3/individual-grid/input.vue
<template>
  <div>
    <ag-grid-vue
      :columnDefs="columnDefs"
      :rowData="rowData"
      @grid-ready="onGridReady"
      :modules="modules"
    ></ag-grid-vue>
  </div>
</template>

<script>
import { AgGridVue } from '@ag-grid-community/vue3';

import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';

export default {
  components: {
    'ag-grid-vue': AgGridVue,
  },
  data() {
    return {
      columnDefs: [],
      rowData: [],
      modules: [ClientSideRowModelModule],
    };
  },
  methods: {
    onGridReady(params) {
      console.log("Hello, world!");
    },
  },
};
</script>

// packages/codemods/src/versions/31.0.0/transform/rename-grid-options/__fixtures__/scenarios/react/on-row-data-changed/input.jsx
/* eslint-disable */
import { AgGridReact } from '@ag-grid-community/react';
import { useCallback } from 'react';

function MyComponent(props) {
  const onRowDataChanged = useCallback((params) => {
    console.log('onRowDataChanged', params);
  }, []);
  return (
    <div>
      <AgGridReact
        columnDefs={[]}
        rowData={[]}
        onRowDataChanged={onRowDataChanged}
      />
    </div>
  );
}
