// packages/codemods/src/transforms/transform-grid-options-v31/__fixtures__/scenarios/react/enable-chart-tool-panels-button/property/output.jsx
import { AgGridReact } from '@ag-grid-community/react';

function MyComponent(props) {
  const enableChartToolPanelsButton = true;
  return (
    (<div>
      <AgGridReact
        columnDefs={[]}
        rowData={[]}
        suppressChartToolPanelsButton={!enableChartToolPanelsButton}
      />
    </div>)
  );
}

// packages/codemods/src/versions/31.0.0/transform/rename-grid-options/scenarios/vue/sfc/row-data-change-detection-strategy/output.vue
<template>
  <div>
    <ag-grid-vue
      :columnDefs="columnDefs"
      :rowData="rowData"
      
      @grid-ready="onGridReady"
    ></ag-grid-vue>
  </div>
</template>

<script>
import { AgGridVue } from '@ag-grid-community/vue';

export default {
  components: {
    'ag-grid-vue': AgGridVue,
  },
  data() {
    return {
      columnDefs: [],
      rowData: []
    };
  },
  methods: {
    onGridReady(params) {},
  },
};
</script>
