// packages/cli/src/codemods/transforms/transform-sparklines-options-v33-0/__fixtures__/scenarios/frameworks/sparkline-vue-sfc/input.vue
<template>
  <div>
    <ag-grid-vue
      :columnDefs="[[{field: 'test', cellRenderer: 'agSparklineRenderer', cellRendererParams: {sparklineOptions: {type: 'column'}}}]"
      :rowData="rowData"
      @grid-ready="onGridReady"
    ></ag-grid-vue>
    <ag-grid-vue
      :columnDefs="columnDefs"
      :rowData="rowData"
      @grid-ready="onGridReady"
    ></ag-grid-vue>
  </div>
</template>

<script>
import { AgGridVue } from '@ag-grid-community/vue';

export default {
  components: {
    'ag-grid-vue': AgGridVue,
  },
  data() {
    return {
      columnDefs: [{field: 'test', cellRenderer: 'agSparklineRenderer', cellRendererParams: {sparklineOptions: {type: 'column'}}}],
      rowData: [],
    };
  },
  methods: {
    onGridReady(params) {
    },
  },
};
</script>

// packages/cli/src/codemods/transforms/transform-sparklines-options-v33-0/__fixtures__/scenarios/frameworks/sparkline-jsx/input.jsx
import { AgGridReact } from '@ag-grid-community/react';

function MyComponent(props) {

  const shouldntChange0 = {
    sparklineOptions: {
      type: 'column'
    }
  }

  const anotherColumn = {
    field: 'test',
    cellRenderer: 'agSparklineCellRenderer',
    cellRendererParams: {
      sparklineOptions: {
        type: 'column'
      }
    }
  }

  return (
    <div>
      <AgGridReact columnDefs={[{
        field: 'test',
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
          sparklineOptions: {
            type: 'line'
          }
        }
      }, {
        field: 'test',
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
          sparklineOptions: {
            type: 'area'
          }
        }
      }, {
        field: 'test',
        cellRenderer: 'agSparklineCellRenderer',
        sparklineOptions: {
          type: 'bar'
        }
      }, {
        field: 'test',
        cellRenderer: 'agSparklineCellRenderer',
        cellRendererParams: {
          sparklineOptions: {
            type: 'column'
          }
        }
      }, anotherColumn, {
        field: 'test',
        cellRenderer: 'agSparklineCellRenderer',
        sparklineOptions: {
          type: 'column'
        }
      }, {
        field: 'test',
        cellRenderer: 'agSparklineCellRenderer',
        sparklineOptions: {
          type: 'asdadasqda'
        }
      }]} rowData={[]}/>
    </div>
  );
}
