// packages/cli/src/codemods/transforms/transform-modules-to-packages-v33/__fixtures__/scenarios/vue3/module-registry/input.vue
<template>
  <div>
    <ag-grid-vue
      :columnDefs="columnDefs"
      :rowData="rowData"
      @grid-ready="onGridReady"
    ></ag-grid-vue>
  </div>
</template>

<script>
import { AgGridVue } from '@ag-grid-community/vue3';

import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
import { ModuleRegistry } from '@ag-grid-community/core';

ModuleRegistry.registerModules([ClientSideRowModelModule]);

export default {
  components: {
    'ag-grid-vue': AgGridVue,
  },
  data() {
    return {
      columnDefs: [],
      rowData: [],
    };
  },
  methods: {
    onGridReady(params) {
      console.log("Hello, world!");
    },
  },
};
</script>

// packages/cli/src/codemods/transforms/transform-modules-to-packages-v33/__fixtures__/scenarios/react/module-registry/input.jsx
import { useState } from 'react';

import { AgGridReact } from '@ag-grid-community/react';
import { ModuleRegistry } from '@ag-grid-community/core';
import { ClientSideRowModelModule } from '@ag-grid-community/client-side-row-model';
import { StatusBarModule } from '@ag-grid-enterprise/status-bar';

ModuleRegistry.registerModules([ClientSideRowModelModule, StatusBarModule]);

import '@ag-grid-community/styles/ag-grid.css';
import '@ag-grid-community/styles/ag-theme-quartz.css';

import { LicenseManager } from '@ag-grid-enterprise/core';
LicenseManager.setLicenseKey('<your license key>');

function App() {
  return <div></div>;
}

export default App;
