// packages/codemods/src/versions/31.0.0/transform/rename-grid-options/scenarios/react/advanced-filter-model/specified/output.jsx
/* eslint-disable */
import { AgGridReact } from '@ag-grid-community/react';

function MyComponent(props) {
  return (
    (<div>
      <AgGridReact
        columnDefs={[]}
        rowData={[]}
        initialState={{
          filter: {
            advancedFilterModel: {
              filterType: 'join',
              type: 'AND',
              conditions: []
            }
          }
        }}
      />
    </div>)
  );
}

// packages/codemods/src/versions/31.0.0/transform/rename-grid-options/__fixtures__/scenarios/vue/sfc/advanced-filter-model/specified/output.vue
<template>
  <div>
    <ag-grid-vue
      :columnDefs="columnDefs"
      :rowData="rowData"
      :initialState="advancedFilterModel"
      @grid-ready="onGridReady"
    ></ag-grid-vue>
  </div>
</template>

<script>
import { AgGridVue } from '@ag-grid-community/vue';

export default {
  components: {
    'ag-grid-vue': AgGridVue,
  },
  data() {
    return {
      columnDefs: [],
      rowData: [],
      advancedFilterModel: {
        filterType: 'join',
        type: 'AND',
        conditions: [],
      },
    };
  },
  methods: {
    onGridReady(params) {
      this.advancedFilterModel = {
        filterType: 'join',
        type: 'AND',
        conditions: [],
      };
    },
  },
};
</script>
