// packages/codemods/src/transforms/migrate-legacy-column-api-v31/__fixtures__/scenarios/vue/sfc/direct-event-property-accessor/output.vue
<template>
  <div>
    <ag-grid-vue
      :columnDefs="columnDefs"
      :rowData="rowData"
      @grid-ready="onGridReady"
    ></ag-grid-vue>
  </div>
</template>

<script>
import { AgGridVue } from '@ag-grid-community/vue';

export default {
  components: {
    'ag-grid-vue': AgGridVue,
  },
  data() {
    return {
      columnDefs: [],
      rowData: null,
    };
  },
  methods: {
    onGridReady(params) {
      fetch('https://www.ag-grid.com/example-assets/olympic-winners.json')
        .then((resp) => resp.json())
        .then((data) => {
          this.rowData = data;
          params.api.resetColumnState();
        });
    },
  },
};
</script>

// packages/codemods/src/transforms/migrate-legacy-column-api-v31/__fixtures__/scenarios/angular/aliased-destructured-event-property-accessor/output.component.ts
// @ts-nocheck
import { ColDef, ColGroupDef, GridReadyEvent } from '@ag-grid-community/core';
import { HttpClient } from '@angular/common/http';
import { Component } from '@angular/core';
import { IOlympicData } from './interfaces';

@Component({
  selector: 'my-app',
  template: `
    <div>
      <ag-grid-angular
        [columnDefs]="columnDefs"
        [rowData]="rowData"
        (gridReady)="onGridReady($event)"
      ></ag-grid-angular>
    </div>
  `,
})
export class AppComponent {
  public columnDefs: (ColDef | ColGroupDef)[] = [];
  public rowData!: IOlympicData[];

  constructor(private http: HttpClient) {}

  onGridReady(params: GridReadyEvent<IOlympicData>) {
    const { api: gridApi } = params;
    this.http
      .get<IOlympicData[]>('https://www.ag-grid.com/example-assets/olympic-winners.json')
      .subscribe((data) => {
        this.rowData = data;
        gridApi.resetColumnState();
      });
  }
}
